package com.livescore.backend.Service;

import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import com.livescore.backend.Entity.Match;
import com.livescore.backend.Interface.MatchInterface;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@Service
public class ScorecardPdfService {

    @Autowired
    private MatchInterface matchInterface;

    @Autowired
    private PlayerInningsService playerInningsService;

    public byte[] generateScorecardPdf(Long matchId) throws Exception {
        Optional<Match> matchOpt = matchInterface.findById(matchId);
        if (matchOpt.isEmpty()) {
            throw new Exception("Match not found");
        }
        Match match = matchOpt.get();

        Long team1Id = match.getTeam1().getId();
        Long team2Id = match.getTeam2().getId();

        // Fetch scorecards
        Map<String, Object> scorecard1 = fetchScorecardMap(matchId, team1Id);
        Map<String, Object> scorecard2 = fetchScorecardMap(matchId, team2Id);

        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PdfWriter writer = new PdfWriter(baos);
        PdfDocument pdf = new PdfDocument(writer);
        Document document = new Document(pdf, PageSize.A4);
        
        DeviceRgb redColor = new DeviceRgb(220, 38, 38); // #DC2626

        // Header
        Paragraph header = new Paragraph("BIIT SPORTS")
                .setFontColor(redColor)
                .setFontSize(24)
                .setBold()
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(0);
        document.add(header);

        Paragraph subHeader = new Paragraph("MATCH SCORECARD")
                .setFontSize(16)
                .setBold()
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(15);
        document.add(subHeader);

        // Match Info Table
        Table infoTable = new Table(UnitValue.createPercentArray(new float[]{20, 30, 20, 30}))
                .useAllAvailableWidth()
                .setMarginBottom(20);

        infoTable.addCell(createCell("Match ID:", true, null));
        infoTable.addCell(createCell(String.valueOf(match.getId()), false, null));
        infoTable.addCell(createCell("Date:", true, null));
        infoTable.addCell(createCell(match.getDate() != null ? match.getDate().toString() : "N/A", false, null));

        infoTable.addCell(createCell("Venue:", true, null));
        infoTable.addCell(createCell(match.getVenue() != null ? match.getVenue() : "N/A", false, null));
        infoTable.addCell(createCell("Overs:", true, null));
        infoTable.addCell(createCell(match.getOvers() != 0 ? String.valueOf(match.getOvers()) : "N/A", false, null));

        infoTable.addCell(createCell("Tournament:", true, null));
        infoTable.addCell(createCell(match.getTournament() != null ? match.getTournament().getName() : "N/A", false, null));
        infoTable.addCell(createCell("Teams:", true, null));
        infoTable.addCell(createCell(match.getTeam1().getName() + " vs " + match.getTeam2().getName(), false, null));

        document.add(infoTable);

        // Team 1 Scorecard
        renderTeamScorecard(document, match.getTeam1().getName(), scorecard1, redColor);
        document.add(new Paragraph("\n"));
        // Team 2 Scorecard
        renderTeamScorecard(document, match.getTeam2().getName(), scorecard2, redColor);

        // Footer
        Paragraph footer = new Paragraph("Generated by BIIT Sports")
                .setFontSize(10)
                .setFontColor(ColorConstants.GRAY)
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginTop(30);
        document.add(footer);

        document.close();
        return baos.toByteArray();
    }

    private void renderTeamScorecard(Document document, String teamName, Map<String, Object> scorecard, DeviceRgb headerColor) {
        // Section Header
        Table sectionHeader = new Table(UnitValue.createPercentArray(new float[]{100}))
                .useAllAvailableWidth()
                .setMarginBottom(10);
        
        Cell headerCell = new Cell()
                .add(new Paragraph(teamName.toUpperCase() + " INNINGS").setBold().setFontColor(ColorConstants.WHITE))
                .setBackgroundColor(headerColor)
                .setTextAlignment(TextAlignment.CENTER)
                .setPadding(5);
        sectionHeader.addCell(headerCell);
        document.add(sectionHeader);

        if (scorecard == null || scorecard.isEmpty()) {
            document.add(new Paragraph("No scorecard data available.").setItalic().setMarginBottom(20));
            return;
        }

        // Batting Table
        Table battingTable = new Table(UnitValue.createPercentArray(new float[]{40, 12, 12, 12, 12, 12}))
                .useAllAvailableWidth()
                .setMarginBottom(15);
        
        // Batting Header
        battingTable.addHeaderCell(createHeaderCell("Batter"));
        battingTable.addHeaderCell(createHeaderCell("R"));
        battingTable.addHeaderCell(createHeaderCell("B"));
        battingTable.addHeaderCell(createHeaderCell("4s"));
        battingTable.addHeaderCell(createHeaderCell("6s"));
        battingTable.addHeaderCell(createHeaderCell("SR"));

        List<Map<String, Object>> batters = (List<Map<String, Object>>) scorecard.get("batsmanScores");
        if (batters != null) {
            for (Map<String, Object> batter : batters) {
                battingTable.addCell(createCell(String.valueOf(batter.get("name")), false, null));
                battingTable.addCell(createCell(String.valueOf(batter.get("runs")), false, TextAlignment.CENTER));
                battingTable.addCell(createCell(String.valueOf(batter.get("balls")), false, TextAlignment.CENTER));
                battingTable.addCell(createCell(String.valueOf(batter.get("fours")), false, TextAlignment.CENTER));
                battingTable.addCell(createCell(String.valueOf(batter.get("sixes")), false, TextAlignment.CENTER));
                battingTable.addCell(createCell(formatDouble(batter.get("strikeRate")), false, TextAlignment.CENTER));
            }
        }
        document.add(battingTable);

        // Bowling Table
        Table bowlingTable = new Table(UnitValue.createPercentArray(new float[]{40, 15, 15, 15, 15}))
                .useAllAvailableWidth()
                .setMarginBottom(15);
        
        bowlingTable.addHeaderCell(createHeaderCell("Bowler"));
        bowlingTable.addHeaderCell(createHeaderCell("O"));
        bowlingTable.addHeaderCell(createHeaderCell("W"));
        bowlingTable.addHeaderCell(createHeaderCell("EC"));
        bowlingTable.addHeaderCell(createHeaderCell("RC"));

        List<Map<String, Object>> bowlers = (List<Map<String, Object>>) scorecard.get("bowlerScores");
        if (bowlers != null) {
            for (Map<String, Object> bowler : bowlers) {
                bowlingTable.addCell(createCell(String.valueOf(bowler.get("name")), false, null));
                String overs = String.valueOf((int)bowler.get("ballsBowled")/6) + "." + String.valueOf((int)bowler.get("ballsBowled")%6);
                bowlingTable.addCell(createCell(overs, false, TextAlignment.CENTER));
                bowlingTable.addCell(createCell(String.valueOf(bowler.get("wickets")), false, TextAlignment.CENTER));
                bowlingTable.addCell(createCell(formatDouble(bowler.get("economy")), false, TextAlignment.CENTER));
                bowlingTable.addCell(createCell(String.valueOf(bowler.get("runsConceded")), false, TextAlignment.CENTER));
            }
        }
        document.add(bowlingTable);

        // Totals Row
        Table totalsTable = new Table(UnitValue.createPercentArray(new float[]{25, 25, 25, 25}))
                .useAllAvailableWidth()
                .setMarginBottom(20);
        
        totalsTable.addCell(createCell("Extras: " + scorecard.get("extras"), true, null));
        totalsTable.addCell(createCell("Total: " + scorecard.get("totalRuns"), true, null));
        totalsTable.addCell(createCell("Wickets: " + scorecard.get("wickets"), true, null));
        totalsTable.addCell(createCell("Overs: " + scorecard.get("overs") + "." + scorecard.get("balls"), true, null));
        
        document.add(totalsTable);

        // Fall of Wickets Table
        List<Map<String, Object>> fowList = (List<Map<String, Object>>) scorecard.get("fallOfWickets");
        if (fowList != null && !fowList.isEmpty()) {
            document.add(new Paragraph("FALL OF WICKETS").setBold().setMarginTop(10).setMarginBottom(5));
            Table fowTable = new Table(UnitValue.createPercentArray(new float[]{15, 25, 20, 40}))
                    .useAllAvailableWidth()
                    .setMarginBottom(15);
            fowTable.addHeaderCell(createHeaderCell("Wicket"));
            fowTable.addHeaderCell(createHeaderCell("Score"));
            fowTable.addHeaderCell(createHeaderCell("Over"));
            fowTable.addHeaderCell(createHeaderCell("Batter"));
            
            for (Map<String, Object> fow : fowList) {
                fowTable.addCell(createCell(String.valueOf(fow.get("wicketNumber")), false, TextAlignment.CENTER));
                fowTable.addCell(createCell(String.valueOf(fow.get("score")), false, TextAlignment.CENTER));
                fowTable.addCell(createCell(String.valueOf(fow.get("over")), false, TextAlignment.CENTER));
                fowTable.addCell(createCell(String.valueOf(fow.get("playerName")), false, null));
            }
            document.add(fowTable);
        }

        // Partnerships Table
        List<Map<String, Object>> partnerships = (List<Map<String, Object>>) scorecard.get("partnerships");
        if (partnerships != null && !partnerships.isEmpty()) {
            document.add(new Paragraph("PARTNERSHIPS").setBold().setMarginTop(10).setMarginBottom(5));
            Table pTable = new Table(UnitValue.createPercentArray(new float[]{40, 20, 20, 20}))
                    .useAllAvailableWidth()
                    .setMarginBottom(15);
            pTable.addHeaderCell(createHeaderCell("Batters"));
            pTable.addHeaderCell(createHeaderCell("Runs"));
            pTable.addHeaderCell(createHeaderCell("Balls"));
            pTable.addHeaderCell(createHeaderCell("Not Out"));
            
            for (Map<String, Object> p : partnerships) {
                String batterNames = String.valueOf(p.get("batter1")) + " & " + String.valueOf(p.get("batter2"));
                pTable.addCell(createCell(batterNames, false, null));
                pTable.addCell(createCell(String.valueOf(p.get("runs")), false, TextAlignment.CENTER));
                pTable.addCell(createCell(String.valueOf(p.get("balls")), false, TextAlignment.CENTER));
                
                boolean isNotOut = false;
                if (p.get("notOut") != null) {
                    isNotOut = Boolean.parseBoolean(String.valueOf(p.get("notOut")));
                } else if (p.get("isNotOut") != null) {
                    isNotOut = Boolean.parseBoolean(String.valueOf(p.get("isNotOut")));
                }
                
                pTable.addCell(createCell(isNotOut ? "Yes" : "No", false, TextAlignment.CENTER));
            }
            document.add(pTable);
        }
    }

    private Cell createHeaderCell(String text) {
        return new Cell().add(new Paragraph(text).setBold())
                .setBackgroundColor(ColorConstants.LIGHT_GRAY)
                .setTextAlignment(TextAlignment.CENTER)
                .setPadding(5);
    }

    private Cell createCell(String text, boolean isBold, TextAlignment alignment) {
        Paragraph p = new Paragraph(text);
        if (isBold) p.setBold();
        if (alignment != null) p.setTextAlignment(alignment);
        return new Cell().add(p).setPadding(5);
    }

    private String formatDouble(Object val) {
        if (val == null) return "0.00";
        try {
            double d = Double.parseDouble(String.valueOf(val));
            return String.format("%.2f", d);
        } catch (Exception e) {
            return "0.00";
        }
    }

    private Map<String, Object> fetchScorecardMap(Long matchId, Long teamId) {
        try {
            ResponseEntity<?> response = playerInningsService.getScorecard(matchId, teamId);
            if (response.getStatusCode().is2xxSuccessful() && response.getBody() != null) {
                System.out.println("Fetched scorecard for team " + teamId + ": " + response.getBody());
                com.fasterxml.jackson.databind.ObjectMapper mapper = new com.fasterxml.jackson.databind.ObjectMapper();
                return mapper.convertValue(response.getBody(), new com.fasterxml.jackson.core.type.TypeReference<Map<String, Object>>() {});
            }
        } catch (Exception e) {
            System.err.println("Failed to fetch scorecard for match " + matchId + " team " + teamId);
            e.printStackTrace();
        }
        return null;
    }
}
